Repository iTjuana/itj-library, pull requests merged in 2023-11, with the labels that each got.

#93 Chore/db changes 92
  .vscode/settings.json
  CONTRIBUTING.md
  prisma-erd.png
  prisma/schema.prisma
  src/pages/account.tsx
  src/pages/book/[book].tsx
  src/pages/catalog.tsx
  src/server/api/routers/books.ts
  src/server/api/routers/inventory.ts
  src/server/api/routers/users.ts
Labels: Backend

#96 Add filter functionality to inventory page
  src/components/filters.tsx
  src/pages/catalog.tsx
  src/server/api/routers/inventory.ts
Labels: enhancement

#98 :lock: Add authorization to manage page
  prisma-erd.png
  prisma/schema.prisma
  src/components/navbar.tsx
  src/pages/manage.tsx
  src/server/auth.ts
  utils/enum.ts
Labels: required, Backend
