Repository iTjuana/itj-library, pull requests merged in 2023-05, with the labels that each got.

#27 :sparkles: Update env example for providers to use
  .env.example
  src/env.mjs
Labels: required

#28 :green_heart: Testing which workflow github actions runs
  .env.example
  .github/workflows/lint.yml
Labels: bug, question

#34 :hammer: Refactor workflows and verify new tests
  .github/workflows/lint.yml
  .github/workflows/test.yml
  package.json
Labels: enhancement

#35 Feature database
  prisma/schema.prisma
Labels: beginner
